<div class="container theme-showcase">
    <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-xs-12 col-sm-9">
            <div class="row">
                <?php foreach ($this->SelectedTag as $tags) { ?>
                    <div class="col-xs-6 col-lg-4">
                        <h2><?=$tags['title']?></h2>
                        <p><?=$this->restrictText($tags['recipe'],250)?></p>
                        <p><a class="btn btn-default" href="<?=$this->baseUrl()?>/read/<?=$this->replaceOnLink($tags['title'])?>" role="button">Zobacz Wpis »</a></p>
                    </div>
                <?php } ?>
            </div><!--/row-->
        </div><!--/.col-xs-12.col-sm-9-->
        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
            <div class="list-group">
                <?=$this->partialLoop('category/get-tags.phtml',$this->getTags); ?>
            </div>
        </div>
    </div>
</div>