<div class="container theme-showcase">
    <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-sm-8 blog-main">
            <div class="row">
               <?php foreach ($this->SelectedTag as $tags) :  ?>
                    <div class="col-xs-6 col-lg-4">
                        <h2><?=$tags['title']?></h2>
                        <p><?=$this->restrictText($tags['recipe'],250)?></p>
                        <p><a class="btn btn-default" href="<?=$this->baseUrl()?>/read/<?=$this->replaceOnLink($tags['title'])?>" role="button">Zobacz Wpis »</a></p>
                    </div>
                <?php endforeach; ?>
            </div><!--/row-->
        </div><!--/.col-xs-12.col-sm-9-->
        <div class="col-sm-4 aso-col-sm-nav" id="sidebar" role="navigation">
            <ul class="list-group">
                <?php foreach ($this->getTags as $tag) : ?>
                    <a href="<?=$this->baseUrl().'/category/byTag/'.$this->replaceOnLink($tag)?>" class="list-group-item <?=(Zend_Controller_Front::getInstance()->getRequest()->getParam('tag') == $this->replaceOnLink($tag)) ? "active" : ""; ?>">
                        <?=$tag?>
                        <span class="badge"><?=$this->category_count?></span>
                    </a>
                <?php endforeach; ?>
<!--                --><?//=$this->partialLoop('category/get-tags.phtml', array('tages' => $this->getTags)); ?>
            </ul>
        </div>
    </div>
</div>