<div class="container theme-showcase">
    <div class="row row-offcanvas row-offcanvas-right">
        <div class="col-sm-8 blog-main">
            <div class="row">
                <?php foreach ($this->SelectedCategory as $categories) : ?>
                    <div class="col-xs-6 col-lg-4">
                        <h2><?=$categories['title']?></h2>
                        <p><?=$this->restrictText($categories['recipe'],250)?></p>
                        <p><a class="btn btn-default" href="<?=$this->baseUrl()?>/read/<?=$this->replaceOnLink($categories['title'])?>" role="button">Zobacz Wpis »</a></p>
                    </div>
                <?php endforeach; ?>
            </div><!--/row-->
        </div><!--/.col-xs-12.col-sm-9-->
        <div class="col-sm-4 aso-col-sm-nav" id="sidebar" role="navigation">
            <div class="list-group">
                <?=$this->partialLoop('category/get-category.phtml',$this->Category); ?>
            </div>
        </div>
    </div>
</div>