<?php if ($this->hotIndex != NULL) : ?>
<div class="container aso-container">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <?php $h = 0;  foreach ($this->hotIndex as $hots) : ?>
                <li data-target="#carousel-example-generic" data-slide-to="<?=$h++?>" class="<?=($h == 1) ? "active" : ""?>"></li>
            <?php endforeach; ?>
        </ol>
        <div class="carousel-inner" role="listbox">
            <?php $h = 0;
            foreach ($this->hotIndex as $hots_display) :
                preg_match_all('/<img.*src=\"(.*)\".*>/iU', $hots_display['recipe'], $images);
                if (count($images[0]) > 0) :
                    $min = 0;
                    $max = count($images[1]) - 1;
                    $linkImage[$h] = $images[1][rand ($min ,$max)];
                endif;
                ?>
            <div class="navbar-default item <?=($h == 0) ? "active" : ""?>">
                <img data-src="holder.js/auto/auto/#11<?=$h?>:#11<?=$h?>/" alt="" style="max-width:1140px; max-height:500px; min-width:100%; min-height:500px; overflow: hidden; background: url(<?=$linkImage[$h]?>) no-repeat 50% 50%;" data-holder-rendered="true">
                <div class="container navbar-default">
                    <div class="carousel-caption">
                        <h1><?=$hots_display['title']?></h1>
                        <p><a class="btn btn-lg btn-primary" href="<?=$this->baseUrl()?>/read/<?=$this->replaceOnLink($hots_display['title'])?>" role="button">Przejdź do wpisu</a></p>
                    </div>
                </div>
            </div>
                <?php $h++ ?>
            <?php endforeach; ?>
        </div>
    </div>
</div>
<?php endif; ?>
<div class="container theme-showcase" role="main">
    <div class="row">
        <div class="col-sm-8 blog-main">
            <?php if (($this->Recipes) != NULL) : $i = 0; ?>
                <?php foreach ($this->Recipes as $values) : ?>
                    <?php if($i%2 == 0) : ?>
                        <?=$this->partial('index/recipe/recipeIndexL.phtml', $values); ?>
                    <?php else : ?>
                        <?=$this->partial('index/recipe/recipeIndexR.phtml', $values); ?>
                    <?php
                    endif;
                    echo '<hr class="featurette-divider">';
                    $i++;
                endforeach;
            else: ?>
                <div class="alert alert-info" role="alert">
                    <p>Nie dodano jeszcze żandego przepisu do strony.</p>
                    <?php if ($this->facebook != null) : ?>
                    <p>Zapraszamy później, bądź na naszego Facebook'a.</p>
                    <?php endif; ?>
                </div>
                <?=$this->render('facebook.phtml'); ?>
            <?php endif ?>

        </div>
        <?=$this->render('sidebar.phtml'); ?>
    </div>
    <?php if (($this->Recipes) != NULL) : ?>
    <nav>
        <ul class="pager">
            <?php
            $next = $this->page+1;
            $prev = $this->page-1;
            ?>
            <li class="next <?=($this->count <= MAX_LIMIT_INDEX) ? "disabled" : "" ?>">
                <?php if(($this->count <= MAX_LIMIT_INDEX)) : ?>
                    <a href="#">Starszey Wpisy &#187;</a>
                <?php else : ?>
                    <a href="<?=$this->baseUrl()?><?=($this->count <= MAX_LIMIT_INDEX) ? null : "/page/$next" ?>">Starze Wpisy &#187;</a>
                <?php endif; ?>
            </li>
            <li class="previous <?=($this->page <= 0) ? "disabled" : "" ?> ">
                <?php if(($this->page <= 0)) : ?>
                    <a href="#">&#171; Nowsze Wpisy</a>
                <?php else : ?>
                    <a href="<?=$this->baseUrl()?><?=($this->page <= 0) ? null : "/page/$prev" ?>">&#171; Nowsze Wpisy</a>
                <?php endif; ?>
            </li>
        </ul>
    </nav>
    <?php endif; ?>

<!--    <script>-->
<!--    $(document).ready(function() {-->
<!--        $('#editor').summernote(-->
<!--            {height: 150}-->
<!--        );-->
<!--    });-->
<!--    </script>-->
<!--    <div class="modal fade bs-example-modal-lg" id="bs-example-modal-edit-post" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">-->
<!--        <form class="form-horizontal" role="form" id="form" method="post" action="--><?//=DEF_CONTROLER__LOGIN?><!--">-->
<!--        <div class="modal-dialog modal-lg">-->
<!--            <div class="modal-content">-->
<!--		<div class="modal-header">-->
<!--                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>-->
<!--                    <h4 class="modal-title" id="myModalLabel">Modal title</h4>-->
<!--                </div>-->
<!--                <div class="modal-body">-->
<!--                    <div id="alerts"></div>-->
<!--                    <textarea id="editor" contenteditable="true" name="editor" style="overflow: auto"></textarea>-->
<!--                </div>-->
<!--                <div class="modal-footer">-->
<!--                    <button type="submit" class="btn btn-primary">Save changes</button>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--        </form>-->
<!--    </div>-->
<!--    <input type="button" class="btn glyphicon-edit" data-toggle="modal" data-target="#bs-example-modal-edit-post"/>-->
</div>