        <div class="col-sm-8 blog-main">
            <?php if (($this->Recipes) != NULL) : $i = 0; ?>
                <?php foreach ($this->Recipes as $values) : ?>
                    <?php if($i%2 == 0) : ?>
                        <?=$this->partial('index/recipe/recipeIndexL.phtml', $values); ?>
                    <?php else : ?>
                        <?=$this->partial('index/recipe/recipeIndexR.phtml', $values); ?>
                    <?php
                    endif;
                    echo '<hr class="featurette-divider">';
                    $i++;
                endforeach;
            else: ?>
                <div class="alert alert-info" role="alert">
                    <p>Nie dodano jeszcze żandego przepisu do strony.</p>
                    <?php if ($this->facebook != null) : ?>
                    <p>Zapraszamy później, bądź na naszego Facebook'a.</p>
                    <?php endif; ?>
                </div>
                <?=$this->render('facebook.phtml'); ?>
            <?php endif ?>
        </div>
<!--    <script>-->
<!--    $(document).ready(function() {-->
<!--        $('#editor').summernote(-->
<!--            {height: 150}-->
<!--        );-->
<!--    });-->
<!--    </script>-->
<!--    <div class="modal fade bs-example-modal-lg" id="bs-example-modal-edit-post" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">-->
<!--        <form class="form-horizontal" role="form" id="form" method="post" action="--><?//=DEF_CONTROLER__LOGIN?><!--">-->
<!--        <div class="modal-dialog modal-lg">-->
<!--            <div class="modal-content">-->
<!--		<div class="modal-header">-->
<!--                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>-->
<!--                    <h4 class="modal-title" id="myModalLabel">Modal title</h4>-->
<!--                </div>-->
<!--                <div class="modal-body">-->
<!--                    <div id="alerts"></div>-->
<!--                    <textarea id="editor" contenteditable="true" name="editor" style="overflow: auto"></textarea>-->
<!--                </div>-->
<!--                <div class="modal-footer">-->
<!--                    <button type="submit" class="btn btn-primary">Save changes</button>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--        </form>-->
<!--    </div>-->
<!--    <input type="button" class="btn glyphicon-edit" data-toggle="modal" data-target="#bs-example-modal-edit-post"/>-->
