<?php $this->placeholder('navigation')->captureStart() ?>
<?php if (($this->Recipes) != NULL) : ?>
    <ul class="pager">
        <?php
        $next = $this->page+1;
        $prev = $this->page-1;
        ?>
        <li class="next <?=($this->count <= MAX_LIMIT) ? "disabled" : "" ?>">
            <?php if(($this->count <= MAX_LIMIT)) : ?>
                <a href="#">Starsze Wpisy &#187;</a>
            <?php else : ?>
                <a href="<?=$this->baseUrl()?><?=($this->count < MAX_LIMIT) ? null : "/page/$next" ?>">Starze Wpisy &#187;</a>
            <?php endif; ?>
        </li>
        <li class="previous <?=($this->page <= 0) ? "disabled" : "" ?> ">
            <?php if(($this->page <= 0)) : ?>
                <a href="#">&#171; Nowsze Wpisy</a>
            <?php else : ?>
                <a href="<?=$this->baseUrl()?><?=($this->page < 0) ? null : "/page/$prev" ?>">&#171; Nowsze Wpisy</a>
            <?php endif; ?>
        </li>
    </ul>
<?php endif; ?>
<?php $this->placeholder('navigation')->captureEnd() ?>