<?php if($this->facebook != NULL) : ?>
    <?php  if($this->additional_settings != NULL) :
        if ($this->isJson($this->additional_settings)) :
            $fb_data = json_decode($this->additional_settings, true);
            switch ($fb_data['fb-box']) :
                case 0:
                    $view = 'fb-page';
                    break;
                case 1:
                    $view = 'fb-like-box';
                    break;
            endswitch;
        else: ?>
            <script>
                $(document).ready( function() {
                    var url='<?=$this->url(array("controller" => "index", "action" => "turn-off-setting"),"default",true);?>/app/facebook';
                    $('body').load(url);
                });
            </script>
        <?php endif;
    endif; ?>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v2.3";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>
    <div class="<?=$view?>" data-href="<?=$this->facebook?>" data-layout="standard" data-share="true"  data-colorscheme="light" data-width="500" data-heigt="650" data-hide-cover="false" data-show-facepile="false" data-show-posts="false">
        <div class="fb-xfbml-parse-ignore">
            <blockquote cite="<?=$this->facebook?>">
                <a href="<?=$this->facebook?>"><?=$this->headTitle($this->title)?></a>
            </blockquote>
        </div>
    </div>
<?php endif; ?>