<?php
$form = $this->form;
?>
<?php     $pn = 'login_view'; ?>
<div class="<?=$pn?> modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <form class="form-horizontal" role="form" id="form" method="post" action="<?=$this->baseUrl().'/'.DEF_CONTROLER__LOGIN?>" >
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Logowanie do strony</h4>
            </div>
            <div class="modal-body">
                    <div class="form-group">
<!--                        --><?//=$form = $this->form;?>
                        <label for="inputEmail3" class="col-sm-2 control-label">Email:</label>
                        <div class="col-sm-10">
                            <?=$form->email;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
                        <div class="col-sm-10">
                            <?=$form->password;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox"  name="remember"> Remember me
                                </label>
                            </div>
                        </div>
                    </div>
                    <a href="<?= $this->googleAuthUrl ?>" class="btn btn-block btn-social btn-google">
                        <i class="fa fa-google-plus"></i> Zaloguj się z konta Google
                    </a>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
                <button type="submit" class="btn btn-primary send">Zaloguj</button>
            </div>
        </div>

    </div>
    </form>
</div>
