<?php
$form = $this->form;
$pn = 'login_view'; ?>
<?php
header('X-Frame-Options: GOFORIT');
?>
<script type="text/javascript">
    $(function() {
        $(".btn-social").click(function(){
            $(this).button('loading').delay(1000).queue(function() {
                var url=$(this).attr('data-target')+ "&output=embed";
                window.open(url, 'mywin', 'left=50%,top=50%,width=500,height=500,toolbar=1,resizable=0');
                $(this).button('reset');
            });
        });
    });
</script>
<div class="<?=$pn?> modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="form-horizontal" role="form" id="form" method="post" action="<?=$this->baseUrl().'/'.DEF_CONTROLER__LOGIN?>" >
                <input type="hidden" name="redirurl" value="<?=$this->serverUrl().$this->url();?>" />
                <div class="modal-header">
                    <h4 class="modal-title">Logowanie do strony</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">Email:</label>
                        <div class="col-sm-10">
                            <?=$form->email;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
                        <div class="col-sm-10">
                            <?=$form->password;?>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox"  name="remember"> Remember me
                                </label>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
                    <button type="submit" class="btn btn-primary send">Zaloguj</button>
                </div>
            </form>
            <div class="modal-body">
                <button data-target="<?=$this->googleAuthUrl?>" class="btn btn-block btn-social btn-google">
                    <i class="fa fa-google-plus"></i> Zaloguj się z konta Google
                </button>
                <button data-target="<?=$this->facebookAuthUrl?>" class="btn btn-block btn-social btn-facebook">
                    <i class="fa fa-facebook"></i> Zaloguj się z Facebook'a
                </button>
            </div>
        </div>
    </div>

</div>
