<div class="col-sm-4">
    <?php if ($this->about["active"] == TRUE) { ?>
        <div class="sidebar-module sidebar-module-inset blog-sidebar">
            <h4>O Mnie</h4>
            <p><?=$this->restrictText($this->about["text"], 100)?></p>
        </div>
    <?php } ?>
    <div class="list-group">
        <?php if ($this->Category != NULL )
            foreach ($this->Category as $category) { ?>
                    <a href="<?=$this->baseUrl()?>/category/<?=$this->replaceOnLink($category['category'])?>" class="list-group-item"><?=$category['category']?>
                        <span class="badge"><?=$category['category_count']?></span>
                    </a>
            <?php   } ?>
    </div>
    <div class="list-group">
        <a href="#" class="list-group-item">
            <h4 class="list-group-item-heading">List group item heading</h4>
            <p class="list-group-item-text">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
        </a>
        <a href="#" class="list-group-item">
            <h4 class="list-group-item-heading">List group item heading</h4>
            <p class="list-group-item-text">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
        </a>
        <a href="#" class="list-group-item">
            <h4 class="list-group-item-heading">List group item heading</h4>
            <p class="list-group-item-text">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
        </a>
        <a href="#" class="list-group-item">
            <h4 class="list-group-item-heading">List group item heading</h4>
            <p class="list-group-item-text">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
        </a>
        <a href="#" class="list-group-item">
            <h4 class="list-group-item-heading">List group item heading</h4>
            <p class="list-group-item-text">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>
        </a>
    </div>
</div>