<div class="col-sm-4">
    <?php if ($this->about["active"] == TRUE) { ?>
        <div class="sidebar-module sidebar-module-inset blog-sidebar">
            <h4>O Mnie</h4>
            <p><?=$this->restrictText($this->about["data"], 100)?></p>
        </div>
    <?php } ?>
    <ul class="list-group">
        <?=$this->partialLoop('category/categorySidebar.phtml',$this->Category); ?>
    </ul>

    <?php if($this->commentsCount) : ?>
    <h2><span class="glyphicon glyphicon-comment btn-lg"></span>Komentarze</h2>
    <nav>
        <ul class="pagination" style="text-align: center">
            <li>&laquo;</li>
            <li>#n</li>
            <li>#n</li>
            <li>#n</li>
            <li>#n</li>
            <li>#n</li>
            <li>#n</li>
            <li>#n</li>
            <li>&raquo;</li>
        </ul>
    </nav>
    <div id="output"></div>
    <script>
        $(".pagination").easyPaging(<?=($this->commentsCount)?>, {
            onSelect: function(page) {
                var url='<?=$this->url(array("controller" => "comments", "action" => "getComments"),"default",true);?>/id/<?=$this->replaceOnLink($this->title)?>/page/'+page;
                $("#output").load(url);
            }
        });
    </script>
        <button type="button" class="btn btn-default" data-toggle="modal" data-target="#add-new-comment">
            <span class="glyphicon glyphicon-comment"></span> Dodaj komentarz
        </button>
        <div class="modal fade" id="add-new-comment" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="exampleModalLabel">Dodaj nowy komentarz</h4>
                    </div>
                    <form role="form" action="<?=$this->url(array("controller" => "comments", "action" => "addComment"),"default",true);?>" id="addCommentForm">
                        <div class="modal-body">
                            <div class="form-group">
                                <label for="recipient-name" class="control-label">Nazwa:</label>
                                <input type="text" class="form-control" id="recipient-name" required="required" >
                            </div>
                            <div class="form-group">
                                <label for="message-text" class="control-label">Komentarz:</label>
                                <textarea class="form-control" id="message-text" required="required"></textarea>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
                            <button type="submit" class="btn btn-primary">Dodaj</button>
                        </div>
                    </form>
                </div>
            </div>
            <script>
                $( "#addCommentForm" ).submit(function( event ) {
                    event.preventDefault();
                    var $form = $( this ),
                        name = $form.find( "input[id='recipient-name']" ).val(),
                        message = $form.find( "textarea[id='message-text']" ).val(),
                        id = '<?=$this->replaceOnLink($this->title)?>',
                        url = $form.attr( "action" );
                        $.post( url, { name: name, message: message, id: id} );
//                    posting.done(function( data ) {
                        $('#add-new-comment').modal('hide');
                        $('body').prepend('<div class="box-message">'+
                            '<div class="alert alert-success" role="alert">'+
                            'Komentarz został dodany'+
                            '</div>'+
                            '</div>');
                        $(".alert-success").delay(5000).fadeTo("slow",0);
                        $(".alert-success").hide(0);
                        $( "input[id='recipient-name']" ).val('');
                        $( "textarea[id='message-text']" ).val('');
//                    });
                });
            </script>
        </div>
    <?php endif; ?>
</div>