<?php

?>
<div class="row featurette">
    <div class="col-md-4">
        <?php preg_match_all('/<img.*src=\"(.*)\".*>/iU', $this->recipe, $images);
        if (empty($images[1][0]) == false) :
            $min = 0;
            $max = count($images[1]) - 1;
            echo $this->dataImage($link = $images[1][rand($min, $max)], $text = null, $width = 230, $height = 230);
        endif;
        ?>
    </div>
    <div class="col-md-8">
        <h3 class="blog-post-title"><?= $this->title ?></h3>

        <p class="blog-post-meta"><?= $this->dateFormat($this->created) ?> <a href="#"><?= $this->autor ?></a></p>

        <p><?= $this->restrictText($this->recipe, 250, true) ?></p>

        <p class="pull-right"><a href="<?= $this->baseUrl() ?>/read/<?= $this->replaceOnLink($this->title) ?>">Czytaj
                całość...</a></p>
        <div style="clear: both"></div>
    </div>
</div>