<style>
    span.glyphicon-thumbs-up, span.glyphicon-thumbs-down:hover {cursor: pointer}
</style>
<div class="list-group">
    <?php if ($this->comments != null) : ?>
        <?php $idBox = 0; ?>
        <?php foreach ($this->comments as $data_comment) : ?>
            <script type="text/javascript">
                $(function() {
                    $(".btn<?=$idBox?>").click(function(){
                        $(this).button('loading').delay(1000).queue(function() {
                            $("#box<?=$idBox?>").html("<?=$data_comment['comment']?></p>");
                            $(this).button('reset');
                            $(this).dequeue();
                            $(".pull<?=$idBox?>").html("");
                        });
                    });
                });
                $('#plus<?=$idBox?>').click(function() {
                    var url='<?=$this->url(array("controller" => "comments", "action" => "vote"),"default",true);?>/plus/<?=$data_comment['id'];?>';
                    $("#plus<?=$idBox?> .small").load(url);
                });
                $('#minus<?=$idBox?>').click(function() {
                    var url='<?=$this->url(array("controller" => "comments", "action" => "vote"),"default",true);?>/minus/<?=$data_comment['id'];?>';
                    $("#minus<?=$idBox?> .small").load(url);
                });
            </script>
            <div class="well">
                <h4 class="list-group-item-heading"><?=$data_comment['userName']?>
                <p class="pull-right btn-sm">
                    <span class="glyphicon glyphicon-thumbs-up" id="plus<?=$idBox?>" style="color: forestgreen"><span class="small" style="color: forestgreen"><?=$data_comment['plus']?></span></span>
                    <span class="glyphicon glyphicon-thumbs-down" id="minus<?=$idBox?>" style="color: red"><span class="small" style="color: red"><?=$data_comment['minus']?></span></span>
                </p></h4>
                <p><?=$data_comment['created']?></p>
                <p id="box<?=$idBox?>" class="list-group-item-text"><?=$this->restrictText($data_comment['comment'],100)?></p>
                <?php if (strlen($data_comment['comment']) > 100):?>
                <p class="pull-right pull<?=$idBox?>">
                    <button type="button" class="btn<?=$idBox?> btn-link" data-loading-text="Ładowanie..." >Czytaj całość <span class="glyphicon glyphicon-chevron-right btn-sm"></span></button>
                    <div style="padding-bottom: 5px"></div>
                </p>
                <?php endif; ?>
            </div>
            <?php $idBox ++ ?>
        <?php endforeach; ?>
    <?php endif; ?>
</div>
