<div role="main">
    <div class="col-sm-8 blog-main">
        <div class="blog-post">
            <h2 class="blog-post-title"><?=$this->title?></h2>
            <p class="blog-post-meta"><?=$this->dateFormat($this->updated)?> <a href="#"><?=$this->autor?></a></p>
            <hr class="featurette-divider">
            <div style="padding: 0 0 20px 0">
            <?=$this->recipe?>
            </div>
            <p class="clearfix">
            <div class="input-group">
                <div class="input-group-addon">Etykiety:</div>
                <div class="tokenfield form-control readonly" style="width: 100%; height: auto;">
                    <?php if ($this->tags != NULL) : ?>
                    <?php foreach ($this->tags as $token) : ?>
                    <div class="token">
                        <a href="<?=$this->baseUrl()?>/category/byTag/<?=$this->replaceOnLink($token)?>">
                            <span class="token-label" style="max-width: 606px; padding-right:4px"><?=$token?></span>
                        </a>
                    </div>
                    <?php endforeach; ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
</div>

