<div class="container theme-showcase" role="main">
    <div class="col-sm-8 blog-main">
        <div class="blog-post">
            <h2 class="blog-post-title"><?=$this->title?></h2>
            <p class="blog-post-meta"><?=$this->dateFormat($this->updated)?> <a href="#"><?=$this->autor?></a></p>
            <hr class="featurette-divider">
            <div style="padding: 0 0 20px 0">
            <?=$this->recipe?>
            </div>
            <p class="clearfix">
            <div class="input-group">
                <div class="input-group-addon">Etykiety:</div>
<!--                <input type="text" class="form-control" id="tokenfield" data-inputType="url" value="--><?//=$this->tags?><!--" />-->
                <div class="tokenfield form-control readonly" style="width: 100%;">
                    <?php foreach ($this->tags as $token) : ?>
                    <div class="token">
                        <a href="<?=$this->baseUrl()?>/category/byTag/<?=$this->replaceOnLink($token)?>">
                            <span class="token-label" style="max-width: 606px; padding-right:4px"><?=$token?></span>
                        </a>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
<!--                <script>-->
<!--                    $('#tokenfield').tokenfield();-->
<!---->
<!--                    $('#tokenfield').tokenfield('readonly');-->
<!--                </script>-->
            </p>

        </div>
    </div>
    <?=$this->render('sidebar.phtml');?>
    </div>
<div class="container">
    <nav>
        <ul class="pager">
            <?php
            $nextRecipe = $this->replaceOnLink($this->nextRecipe);
            $prevRecipe = $this->replaceOnLink($this->prevRecipe);
            ?>
            <li class="next <?=($this->nextRecipe == null) ? "disabled" : "" ?>">
                <?php if(($this->nextRecipe == null)) : ?>
                    <a href="#">Starszy Wpisy &#187;</a>
                <?php else : ?>
                    <a href="<?=$this->baseUrl()?><?=($this->nextRecipe == null) ? null : "/read/$nextRecipe" ?>">Starszy Wpisy &#187;</a>
                <?php endif; ?>
            </li>
            <li class="previous <?=($this->prevRecipe == null) ? "disabled" : "" ?> ">
                <?php if(($this->prevRecipe == null)) : ?>
                    <a href="#">&#171; Nowszy Wpisy</a>
                <?php else : ?>
                    <a href="<?=$this->baseUrl()?><?=($this->prevRecipe == null) ? null : "/read/$prevRecipe" ?>">&#171; Nowszy Wpisy</a>
                <?php endif; ?>
            </li>

        </ul>
    </nav>
</div>