<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php echo $this->headTitle()."\n" ?>
    <?php echo $this->headMeta()."\n" ?>
    <?php echo $this->headLink()."\n" ?>
    <?php echo $this->headStyle()."\n" ?>
    <?php echo $this->headScript()."\n" ?>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<?php if(isset($this->message)) :?>
    <?php $message = $this->message; ?>
    <?php   $text   = $message["message"];
            $style  = $message["style"];
    ?>
    <script>
        $(document).ready(function(){
            $(".alert-<?=$style?>").delay(5000).fadeTo("slow",0);
            $(".alert-<?=$style?>").hide(0);
        });
    </script>
    <div class="box-message">
        <div class="alert alert-<?=$style?>" role="alert">
            <?=$text?>
        </div>
    </div>
<?php endif;?>
<?php $ms = new Zend_Session_Namespace(SESSION_NAMESPACE); ?>
<div class="navbar-wrapper">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">W Moim Magicznym Domu</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <?php   $menu_json = ($this->menu);
                    $i = 0;
                    $j = 0;
                    foreach ($menu_json as $key => $value){
                        ?>
                        <li <?=($menu_json[$i]['dropdown'] != null) ? 'class="dropdown"' : ''; ?>>
                            <a href=".<?=$menu_json[$i]['link']?>"<?=($menu_json[$i]['dropdown'] != null) ? 'class="dropdown-toggle" data-toggle="dropdown"' : ''?>>
                                <?=$menu_json[$i]['name']?><?=($menu_json[$i]['dropdown'] != null) ? '<span class="caret"></span>' : '' ?>
                            </a>
                            <? if($menu_json[$i]['dropdown'] != null) { ?>
                                <ul class="dropdown-menu" role="menu">
                                    <?php foreach($menu_json[$i]['dropdown'] as $drop_value) {
                                        echo '<li><a href=".'.$drop_value['drop_link'].'">'.$drop_value['drop_name'].'</a></li>';
                                        $j++;
                                    }; ?>
                                </ul>
                            <?php } ?>
                        </li>
                        <?php
                        $i++;
                    }
                    ?>
                </ul>
                <div class="nav navbar-nav navbar-right">
                    <form class="navbar-form navbar-left" role="search">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search">
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                    </form>
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=(isset($ms->u_name)) ? $ms->u_name : 'Konto'?> <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <?php if (isset($ms->u_id)) { ?>
                                    <li><a href="/">Dodaj nowy wpis</a></li>
                                    <li><a href="/">Ustawienia</a></li>
                                    <li><a href="login/logout">Wyloguj</a></li>
                                <?php }else{ ?>
                                    <li><a href="#" data-toggle="modal" data-target="#login">Zaloguj</a></li>
                                <?php } ?>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
</div>

<div class="container">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class=""></li>
            <li data-target="#carousel-example-generic" data-slide-to="1" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2" class=""></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="item">
                <img data-src="holder.js/1140x300/auto/#777:#555/text:First slide" alt="First slide [1140x300]" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMTE0MCIgaGVpZ2h0PSI1MDAiIHZpZXdCb3g9IjAgMCAxMTQwIDUwMCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSIxMTQwIiBoZWlnaHQ9IjUwMCIgZmlsbD0iIzc3NyIvPjxnPjx0ZXh0IHg9IjQwMy4xMDkzNzUiIHk9IjI1MCIgc3R5bGU9ImZpbGw6IzU1NTtmb250LXdlaWdodDpib2xkO2ZvbnQtZmFtaWx5OkFyaWFsLCBIZWx2ZXRpY2EsIE9wZW4gU2Fucywgc2Fucy1zZXJpZiwgbW9ub3NwYWNlO2ZvbnQtc2l6ZTo1M3B0O2RvbWluYW50LWJhc2VsaW5lOmNlbnRyYWwiPkZpcnN0IHNsaWRlPC90ZXh0PjwvZz48L3N2Zz4=" data-holder-rendered="true">
                <div class="container">
                    <div class="carousel-caption">
                        <h1>One more for good measure.</h1>
                        <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
                    </div>
                </div>
            </div>
            <div class="item active">
                <img data-src="holder.js/1140x300/auto/#666:#444/text:Second slide" alt="Second slide [1140x300]" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMTE0MCIgaGVpZ2h0PSI1MDAiIHZpZXdCb3g9IjAgMCAxMTQwIDUwMCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSIxMTQwIiBoZWlnaHQ9IjUwMCIgZmlsbD0iIzY2NiIvPjxnPjx0ZXh0IHg9IjM1Mi4wNjI1IiB5PSIyNTAiIHN0eWxlPSJmaWxsOiM0NDQ7Zm9udC13ZWlnaHQ6Ym9sZDtmb250LWZhbWlseTpBcmlhbCwgSGVsdmV0aWNhLCBPcGVuIFNhbnMsIHNhbnMtc2VyaWYsIG1vbm9zcGFjZTtmb250LXNpemU6NTNwdDtkb21pbmFudC1iYXNlbGluZTpjZW50cmFsIj5TZWNvbmQgc2xpZGU8L3RleHQ+PC9nPjwvc3ZnPg==" data-holder-rendered="true">
                <div class="container">
                    <div class="carousel-caption">
                        <h1>One more for good measure.</h1>
                        <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
                    </div>
                </div>
            </div>
            <div class="item">
                <img data-src="holder.js/1140x300/auto/#555:#333/text:Third slide" alt="Third slide [1140x300]" src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMTE0MCIgaGVpZ2h0PSI1MDAiIHZpZXdCb3g9IjAgMCAxMTQwIDUwMCIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+PGRlZnMvPjxyZWN0IHdpZHRoPSIxMTQwIiBoZWlnaHQ9IjUwMCIgZmlsbD0iIzU1NSIvPjxnPjx0ZXh0IHg9IjM5MS4zNTkzNzUiIHk9IjI1MCIgc3R5bGU9ImZpbGw6IzMzMztmb250LXdlaWdodDpib2xkO2ZvbnQtZmFtaWx5OkFyaWFsLCBIZWx2ZXRpY2EsIE9wZW4gU2Fucywgc2Fucy1zZXJpZiwgbW9ub3NwYWNlO2ZvbnQtc2l6ZTo1M3B0O2RvbWluYW50LWJhc2VsaW5lOmNlbnRyYWwiPlRoaXJkIHNsaWRlPC90ZXh0PjwvZz48L3N2Zz4=" data-holder-rendered="true">
                <div class="container">
                    <div class="carousel-caption">
                        <h1>One more for good measure.</h1>
                        <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <ol class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li class="active">Home</li>
    </ol>
</div>
<?php echo $this->layout()->content ?>
<div class="container">
    <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&#169; 2014 Company, Inc. &#8226; <a href="#">Privacy</a> &#8226; <a href="#">Terms</a></p>
    </footer>
</div>
</body>
</html>