<!DOCTYPE html>
<html lang="en">
<head>
    <?php echo $this->headTitle()."\n" ?>
    <?php echo $this->headMeta()."\n" ?>
    <?php echo $this->headLink()."\n" ?>
    <?php echo $this->headStyle()."\n" ?>
    <?php echo $this->headScript()."\n" ?>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<?php if(isset($this->message)) :?>
    <?php $message = $this->message; ?>
    <script>
        $(document).ready(function(){
            $(".alert-<?=$message[1]?>").delay(5000).fadeTo("slow",0);
            $(".alert-<?=$message[1]?>").hide(0);
        });
    </script>
    <div class="box-message">
        <div class="alert alert-<?=$message[1]?>" role="alert">
            <?=$message[0]?>
        </div>
    </div>
<?php endif;?>

<?php echo $this->layout()->content ?>
 
</body>
</html>