<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php echo $this->headTitle($this->web_title['data'])."\n" ?>
    <?php echo $this->headMeta()."\n" ?>
    <?php echo $this->headLink()."\n" ?>
    <?php echo $this->headStyle()."\n" ?>
    <?php echo $this->headScript()."\n" ?>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<?=$this->render('login_popup.phtml')?>
<?php if(isset($this->message)) :?>
    <?php $message = $this->message; ?>
    <?php   if (isset($message["message"])) { $text   = $message["message"]; }else{ $text   = ''; };
            if (isset($message["style"])) { $style   = $message["style"]; }else{ $style   = ''; };
    ?>
    <script>
        $(document).ready(function(){
            $(".alert-<?=$style?>").delay(5000).fadeTo("slow",0);
            $(".alert-<?=$style?>").hide(0);

        });
    </script>
    <div class="box-message">
        <div class="alert alert-<?=$style?> pop-up" role="alert">
            <?=$text?>
        </div>
    </div>
<?php endif;?>

<?php $ms = new Zend_Session_Namespace(SESSION_NAMESPACE); ?>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?=$this->baseUrl()?>"><?=$this->web_title['data']?></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="<?=$this->baseUrl()?>">Główna</a></li>
                    <?php if(!empty($this->Category)) : ?>
                    <li class="dropdown">
                        <a href="<?=$this->baseUrl()?>/category" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">Kategorie <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <?=$this->partialLoop('index/menu-category.phtml',$this->Category); ?>
                        </ul>
                    </li>
                    <?php endif; ?>
                    <?php if ($this->about == TRUE) { ?>
                    <li><a href="<?=$this->baseUrl()?>/about">O mnie</a> </li>
                    <?php } ?>
                </ul>
                <div class="nav navbar-nav navbar-right">
                    <form class="navbar-form navbar-left" role="search">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Wpisz szukane słowa...">
                        </div>
                        <button type="submit" class="btn btn-default">Szukaj</button>
                    </form>
                    <ul class="nav navbar-nav">
                        <li class="dropdown">

                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=(isset($ms->u_name)) ? $ms->u_name : 'Konto'?> <span class="caret"></span>
                                <?php if (isset($ms->u_picture) && $ms->u_picture != '') : ?><img class="img-circle aso-img-menu" src="<?=$ms->u_picture?>" alt="Generic placeholder image" width="20" height="20"> <?php endif; ?>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <?php if (isset($ms->u_id)) : ?>
                                    <?php if ($ms->u_role == 1) : ?>
                                        <li><a href="/">Dodaj nowy wpis</a></li>
                                        <li><a href="/">Ustawienia</a></li>
                                    <?php endif; ?>
                                    <li><a href="<?=$this->baseUrl()?>/login/logout">Wyloguj</a></li>
                                <?php else: ?>
                                    <li><a href="#" data-toggle="modal" data-target="#login">Zaloguj</a></li>
                                <?php endif; ?>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
<?php echo $this->placeholder('hotIndex') ?>
<div class="container theme-showcase" role="main">
    <div class="row">
        <div class="container">
            <?php echo $this->layout()->content ?>
            <?php echo $this->placeholder('sidebar') ?>
            <?php echo $this->placeholder('navigation') ?>
    </div>
</div>
<div class="container">
    <hr class="featurette-divider"/>
    <footer>
        <p class="pull-right"><a href="#">&#8593; Wróć na Górę.</a></p>
        <p><?=$this->web_title['data']?> &#8226; <a href="#">Privacy</a> &#8226; <a href="#">Terms</a></p>
        <p class="pull-right">ver. <?=APP_VER?>-2014</p>
    </footer>
</div>
</body>
</html>