<style>
    span.glyphicon-thumbs-up, span.glyphicon-thumbs-down:hover {cursor: pointer}
</style>
<script type="text/javascript">
    $(function() {
        $(".read-more").click(function(){
            $(this).button('loading').delay(1000).queue(function() {
                var url='<?=$this->url(array("controller" => "comments", "action" => "get-comment"),"default",true);?>/id/' + $(this).attr('data-main');
                $("#"+$(this).attr('data-target')).load(url);
                $(this).button('reset');
                $(this).dequeue();
                $($(this)).html("");
            });
        });
    });
    $('.vote-plus').click(function() {
        var url='<?=$this->url(array("controller" => "comments", "action" => "vote"),"default",true);?>/plus/' + $(this).attr('data-main');
        $("#"+$(this).attr('id')+" .small").load(url);
    });
    $('.vote-minus').click(function() {
        var url='<?=$this->url(array("controller" => "comments", "action" => "vote"),"default",true);?>/minus/' + $(this).attr('data-main');
        $("#"+$(this).attr('id')+" .small").load(url);
    });

    $(document).ready(function(){
        $('[data-toggle="popover"]').popover({ html : true, delay: { "show": 500, "hide": 100 }});

    });
</script>
<div class="list-group">

    <?php if ($this->comments != null) : ?>
        <?php $idBox = 0; ?>
        <?php foreach ($this->comments as $data_comment) : ?>
            <div class="well">
                <h4 class="list-group-item-heading"><span data-placement="left" data-toggle="popover" data-trigger="click" data-content='<div class="row">
  <div class="col-md-8">.col-md-8</div>
  <div class="col-md-4">.col-md-4</div>
</div>' data-title="<?=$data_comment['userName']?>"><?=$data_comment['userName']?></span>
                    <?php if (isset($data_comment['picture']) && $data_comment['picture'] != '') : ?><img class="img-circle aso-img-menu" src="<?=$data_comment['picture']?>" width="20" height="20"> <?php endif; ?>
                <p class="pull-right btn-sm">
                    <span class="glyphicon glyphicon-thumbs-up vote-plus" id="plus<?=$idBox?>" data-main="<?=$data_comment['id']?>" style="color: forestgreen"><span class="small" style="color: forestgreen"><?=$data_comment['plus']?></span></span>
                    <span class="glyphicon glyphicon-thumbs-down vote-minus" id="minus<?=$idBox?>" data-main="<?=$data_comment['id']?>" style="color: red"><span class="small" style="color: red"><?=$data_comment['minus']?></span></span>
                </p></h4>
                <p><?=$data_comment['created']?></p>
                <p id="box<?=$idBox?>" class="list-group-item-text"><?=$this->restrictText($data_comment['comment'],100)?></p>
                <?php if (strlen($data_comment['comment']) > 100):?>
                <p class="pull-right pull<?=$idBox?>">
                    <button type="button" class="btn<?=$idBox?> btn-link read-more" data-target="box<?=$idBox?>" data-main="<?=$data_comment['id']?>" data-loading-text="Ładowanie..." >Czytaj całość <span class="glyphicon glyphicon-chevron-right btn-sm"></span></button>
                    <div style="padding-bottom: 5px"></div>
                </p>
                <?php endif; ?>
            </div>
            <?php $idBox ++ ?>
        <?php endforeach; ?>
    <?php endif; ?>
    </div>
</div>
<?php //endif; ?>