<div class="site-wrapper">
    <div class="site-wrapper-inner">
        <div class="cover-container">
            <div class="inner cover">
                <h1 class="cover-heading">Troszeczkę o mnie...</h1>
                <p class="lead"><?=$this->about['text']?></p>
                <p class="lead">
                <div class="alert alert-info" role="alert">
                    <?=$this->render('facebook.phtml'); ?>
                    </div>
                </p>
            </div>
        </div>
    </div>
</div>